spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    enabled: true
    cache: false
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # redis默认情况下有16个分片，这里配置具体使用的分片，默认为0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数(使用负数表示没有限制),默认8
        max-active: 100